---
#
# Ansible managed
#
repository:
  description: The purpose of this role is to make backups of your system.
  homepage: https://buluma.github.io/
  topics: backup, server, system, ansible, molecule, tox, playbook, hacktoberfest
